name: Weekly Momentum Report

on:
  schedule:
    - cron: '30 14 * * 5'  # Every Friday at 14:30 UTC (8 PM IST)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weekly script
      run: python weekly.py > output.txt 2>&1

    - name: Send Telegram report
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Weekly Momentum Stocks Report
        document: output.txt