name: Weekly Momentum Report

on:
  schedule:
    - cron: '30 14 * * 5'  # Every Friday at 14:30 UTC (8 PM IST)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weekly script
      run: python weekly.py > output.txt 2>&1

    - name: Send email report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Weekly Momentum Stocks Report
        body: |
          Weekly Momentum Stocks Report

          Please find the output attached.
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: output.txt